### ISSUE TITLE
Invoke-WebRequest and basic parsing

### ISSUE THREAD

**Issue by daughey** [lanalua/azure-pipeline-variables-updater#1]
I can see that your calls to Invoke-WebRequest are without the -UseBasicParsing switch.  This can cause problems for anyone running an agent on a machine with a version of PowerShell lower than 6.  

It's not a problem for hosted agents and they have the latest powershell and that defaults to basic parsing.

Technically UseBasicParsing is a deprecated switch so I'll leave it to you to decide on whether to include it for backwards compatibility or whether to set a demand on the task to need powershell 6.

**Comment by bcgrillo** [comment]
Hello! If you had the time and you don't mind doing it, could you send me the change for do one of the two options? Thanks in advance

**Comment by bcgrillo** [comment]
Hi @daughey, sorry for the delay... I updated the plugin with the -UseBasicParsing switch for backwards compatibility.

**Comment by daughey** [comment]
Many thank!

Sorry I didn't respond before.  Had problems with my GitHub login at the time then forgot about it when it got resolved.

**Comment by bcgrillo** [comment]
I had to change for another compatibility problem. Now there is a checkbox to decide whether or not you want to use the parameter (by default is no).
