### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by TFO-1** [lanalua/azure-pipeline-variables-updater#2]
I'm trying to use this in our on-prem TFS 2018 Server but get a the error. I have OAuth enabled and "Project Collection Build Service" as Admin.  I've tried the Variable Group ID of "7" (based on the variable group URL) and "KPIDashboard" (the name).  I have PS 5.1 installed.  Any ideas? Do I need https enabled?

2019-09-09T23:14:02.1779273Z Variable name: BuildRev
2019-09-09T23:14:02.1779950Z New value: 1
2019-09-09T23:14:02.1780220Z Variable group URI: http://mytfs2018:8080/tfs/MyCollection/390df539-da72-4ea6-ad2d-6c93e52e92df/_apis/distributedtask/variablegroups/7?api-version=5.0-preview.1
2019-09-09T23:14:02.3089027Z ##[error]The remote server returned an error: (404) Not Found.

**Comment by bcgrillo** [comment]
Hi @TFO-1!

I am sorry, I should have specified that, but the plugin requires the API version 5.0-preview.1 (https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops).

I think that API call is the same in your TFS version, ¿can you try changing the API version in the URL and check if it returns a 404 or some other error?

Thanks in advance.

More references here: https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/update?view=vsts-rest-tfs-4.1

Cheers

**Comment by TFO-1** [comment]
Hi @bgrillo,

Thanks for the quick response.  While trying to do this same task in powershell I discovered I had to use "4.1-preview" API.  Any chance you could parameterize the API version?

Thanks again!

**Comment by bcgrillo** [comment]
Of course! But I will need some days to do that! Sorry!

**Comment by TFO-1** [comment]
No worries!

**Comment by TFO-1** [comment]
I have another question…

Does your updater preserve other variables defined in the Variable group or does it overwrite the whole Variable group? The powershell script I found erases everything and only leaves the variable specified to be updated.


Regards,
Tom

**Comment by bcgrillo** [comment]
Hi @TFO-1! I have updated the extension to the version 0.0.4, that uses the api "4.1-preview". 

About the other variables, the extension read all the variables in the variable group, change the value in the variable that we want, and update all the variable group (with just one value changed).

**Comment by TFO-1** [comment]
Hi,

When click on the "Shared variable updater (preview)" link in Manage Extensions, then select "Manage" on the "Team Foundation Server > Build and release > Shared variable updater (preview)" screen, "Shared variable updater (preview)"  shows "0.0.4"  but the "Update…" option in the drop-list is disabled.  On that same screen, if I select "Install" I get a message saying "The extension is already installed for the collection…"

If I uninstall and reinstall "Shared variable updater (preview)" I still get the error and it's still logging "Variable group URI: http://MyTfs2018:8080/tfs/ActiveDevelopment/390df539-da72-4ea6-ad2d-6c93e52e92df/_apis/distributedtask/variablegroups/7?api-version=5.0-preview.1".


Regards,
Tom

**Comment by bcgrillo** [comment]
Maybe is it a cache bug?
https://stackoverflow.com/questions/48186098/vsts-tfs-extension-reinstall-after-remove-the-extension-already-exists
