### ISSUE TITLE
error with new version 1.0.4

### ISSUE THREAD

**Issue by nisimic** [lanalua/azure-pipeline-variables-updater#4]
Until ~10 days ago we used version 1.0.0 with TFS 2018 without any issues.
Now, with newer version 1.0.4 we started to get an error:
**"A parameter cannot be found that matches parameter name 'UseBasicParsing' "**

Please advise.
Thanks!

**Comment by bcgrillo** [comment]
Hi @nisimic!
First of all, I'm sorry for the inconvenience, I've already solved the bug. Please try the version 1.0.5.

**Comment by nisimic** [comment]
Hi,

Thank you very much for the response and help!
I will try it tomorrow morning and update you accordingly.

Regards,
nisimic

השג את Outlook עבור Android<https://aka.ms/ghei36>

________________________________

**Comment by bcgrillo** [comment]
Ok @nisimic, please, tell me if it is working and, if you are so kind, update your pluign rating in the marketplace. Thanks!

**Comment by nisimic** [comment]
Thank you it is working well again.
As you requested, I will update the rating (didn’t know it is that important…)

Best regards

Confidentiality Notice: This e-mail message, including any attachment thereof, is intended only for the person(s) to whom it is addressed and may contain proprietary, confidential and/or privileged material. Any review, reproduction, dissemination or other use of, or taking any action in reliance upon, this information by persons or entities other than the intended recipient(s), is prohibited. If you received this e-mail in error, please immediately notify the sender by return e-mail, and delete this message from your computer. Thank you.
